import { useDispatch, useSelector } from "react-redux";
import {
  venn_diagram,
  translation,
  shapes,
  rotational_symmetry,
  rotation,
  reflection,
  reflection_symmetry,
  plotting_points,
  perimeter_area,
  perpendicular,
  patterns,
  parallel,
  basic_probability,
  angles,
  triangleSum,
  equation,
  angle_relationship,
  thirty_sixty_ninety,
  fortyfive_fortyfive_ninety,
  aas,
  alternate_interior_angles,
  asa,
  complementary_angles,
  composite_shape,
  conditional_statements,
  congruent_triangles,
  converse,
  corresponding_angles,
  dilation,
  expected_value,
  flow_charts,
  hl,
  inverse_trig,
  multi_step_word_problems,
  naming_angles,
  probability_area_model,
  probability_tree_diagram,
  pythagorean_theorem,
  pythagorean_triples,
  same_side_interior_angles,
  sas,
  similar_triangles_word_problems,
  slope_triangles,
  sss,
  supplementary_angles,
  system_of_equations,
  tangent,
  all_trig_ratios,
  vertical_angles,
  order_of_operations,
  one_step_equations,
  adding_integers,
  rounding,
  evaluating_expressions,
  two_step_equations,
  subtracting_integers,
  multiplying_integers,
  adding_fractions,
  multiplying_fractions,
  reducing_fractions,
  ruler,
  protractor,
} from "../../shared/images";

export const Data = {
  Selector: {
    Chapters: ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight"],
    0: {
      text: [
        "measuring sides",
        "adding integers",
        "order of operations",
        "subtracting integers",
        "measuring angles",
        "adding fractions",
        "plotting points",
        "reducing fractions",
        "graphing lines",
        "evaluating expressions",
        "one-step equations",
        "two-step equations",
        "multiplying integers",
        "rounding",
        "multiplying fractions",
      ],
      diagram: [
        {
          src: ruler,
          text: "measuring sides",
          label: "measuring sides",
        },
        {
          src: adding_integers,
          text: "adding integers",
          label: "adding integers",
        },
        {
          src: order_of_operations,
          text: "order of operations",
          label: "order of operations",
        },
        {
          src: subtracting_integers,
          text: "subtracting integers",
          label: "subtracting integers",
        },
        {
          src: protractor,
          text: "measuring angles",
          label: "measuring angles",
        },
        {
          src: adding_fractions,
          text: "adding fractions",
          label: "adding fractions",
        },
        {
          src: plotting_points,
          text: "plotting points",
          label: "plotting points",
        },
        {
          src: reducing_fractions,
          text: "reducing fractions",
          label: "reducing fractions",
        },
        {
          src: plotting_points,
          text: "graphing lines",
          label: "graphing lines",
        },
        {
          src: evaluating_expressions,
          text: "evaluating expressions",
          label: "evaluating expressions",
        },
        {
          src: one_step_equations,
          text: "one-step equations",
          label: "one-step equations",
        },
        {
          src: two_step_equations,
          text: "two-step equations",
          label: "two-step equations",
        },

        {
          src: multiplying_integers,
          text: "multiplying integers",
          label: "multiplying integers",
        },
        {
          src: rounding,
          text: "rounding",
          label: "rounding",
        },
        {
          src: multiplying_fractions,
          text: "multiplying fractions",
          label: "multiplying fractions",
        },
      ],
    },
    1: {
      text: [
        "symmetry",
        "equations",
        "patterns",
        "angles",
        "sides",
        "shapes",
        "plotting points",
        "area perimeter",
        "reflection",
        "rotation",
        "translation",
        "parallel",
        "perpendicular",
        "rotational symmetry",
        "reflection symmetry",
        "basic probability",
        "venn diagrams",
      ],
      diagram: [
        { src: equation, text: "equations", label: "equations" },
        { src: patterns, text: "patterns", label: "patterns" },
        { src: angles, text: "angles", label: "angles" },
        { src: shapes, text: "shapes", label: "shapes" },
        {
          src: plotting_points,
          text: "plotting_points",
          label: "plotting points",
        },
        {
          src: perimeter_area,
          text: "perimeter_area",
          label: "finding area and perimeter",
        },
        { src: reflection, text: "reflection", label: "reflections" },
        { src: rotation, text: "rotation", label: "rotations" },
        { src: translation, text: "translation", label: "translations" },
        { src: parallel, text: "parallel", label: "parallel lines/slopes" },
        {
          src: perpendicular,
          text: "perpendicular",
          label: "perpendicular lines/slopes",
        },
        {
          src: rotational_symmetry,
          text: "rotational_symmetry",
          label: "rotational symmetry",
        },
        {
          src: reflection_symmetry,
          text: "reflection_symmetry",
          label: "reflection symmetry",
        },
        {
          src: basic_probability,
          text: "basic_probability",
          label: "basic probability",
        },
        {
          src: venn_diagram,
          text: "venn_diagram",
          label: "understanding venn diagrams",
        },
      ],
    },
    2: {
      text: [
        "naming angles",
        "complementary angles",
        "vertical angles",
        "supplementary angles",
        "corresponding angles",
        "conditional statements",
        "alternate-interior angles",
        "same-side interior angles",
        "all angles",
        "system-of-equations",
        "triangle sum",
        "object dimensions",
        "composite shapes",
        "area",
        "triangle inequality",
        "pythagoreon theorem",
      ],
      diagram: [
        { src: naming_angles, text: "naming angles", label: "naming angles" },
        {
          src: complementary_angles,
          text: "complementary angles",
          label: "complementary angles",
        },
        {
          src: vertical_angles,
          text: "vertical angels",
          label: "vertical angles",
        },
        {
          src: supplementary_angles,
          text: "supplementary angles",
          label: "supplementary angles",
        },
        {
          src: corresponding_angles,
          text: "corresponding angles",
          label: "corresponding angles",
        },
        {
          src: conditional_statements,
          text: "conditional statements",
          label: "conditional statements",
        },
        {
          src: alternate_interior_angles,
          text: "alternate_interior angles",
          label: "alternate interior angles",
        },
        {
          src: same_side_interior_angles,
          text: "same_side_interior angles",
          label: "same-side interior angles",
        },
        {
          src: same_side_interior_angles,
          text: "all angles",
          label: "all angles",
        },
        {
          src: system_of_equations,
          text: "system_of_equations",
          label: "system of equations",
        },
        { src: triangleSum, text: "triangle sum", label: "triangle sum" },
        {
          src: perimeter_area,
          text: "object dimensions",
          label: "finding shape dimensions",
        },
        {
          src: composite_shape,
          text: "composite shapes",
          label: "getting area of composite shapes",
        },
        {
          src: pythagorean_theorem,
          text: "pythagoreon theorem",
          label: "pythagorean theorem",
        },
      ],
    },
    3: {
      text: [
        "dilation",
        "similarity",
        "zoom factor",
        "proportions",
        "proportional reasoning",
        "similarity proofs",
        "flow charts",
        "similar-triangles word-problems",
      ],
      diagram: [
        { src: dilation, text: "dilation", label: "dilation" },
        {
          src: similar_triangles_word_problems,
          text: "similarity",
          label: "similarity/zoom factor/proportions",
        },
        { src: flow_charts, text: "flow charts", label: "flow charts" },
      ],
    },
    4: {
      text: [
        "slope triangles",
        "tangent",
        "more tangent",
        "probability area_model",
        "probability tree_diagram",
        "expected value",
      ],
      diagram: [
        {
          src: slope_triangles,
          text: "slope triangles",
          label: "slope triangles",
        },
        { src: tangent, text: "tangent", label: "using tangent" },
        {
          src: probability_area_model,
          text: "probability area_model",
          label: "area model",
        },
        {
          src: probability_tree_diagram,
          text: "probability tree_diagram",
          label: "tree diagram",
        },
        {
          src: expected_value,
          text: "expected value",
          label: "expected value",
        },
      ],
    },
    5: {
      text: [
        "all_trig ratios",
        "inverse trig",
        "trig word-problems",
        "thirty sixty ninety",
        "forty-five forty-five ninety",
        "pythagorean triples",
        "law-of-sines",
        "law-of-cosines",
        "multi-step word-problems",
      ],
      diagram: [
        {
          src: all_trig_ratios,
          text: "all_trig_ratios",
          label: "using all trig ratios",
        },
        { src: inverse_trig, text: "inverse trig", label: "inverse trig" },
        {
          src: similar_triangles_word_problems,
          text: "trig word-problems",
          label: "trig word problems",
        },
        {
          src: thirty_sixty_ninety,
          text: "30-60-90",
          label: "30-60-90 triangles",
        },
        {
          src: fortyfive_fortyfive_ninety,
          text: "45-45-90",
          label: "45-45-90 triangles",
        },
        {
          src: pythagorean_triples,
          text: "pythagorean triples",
          label: "pythagorean triplets",
        },
        {
          src: multi_step_word_problems,
          text: "multi-step word-problems",
          label: "harder word problems",
        },
      ],
    },
    6: {
      text: ["congruent triangles", "sss", "sas", "aas", "hl", "asa", "flowcharts", "converse"],
      diagram: [
        {
          src: congruent_triangles,
          text: "congruent triangles",
          label: "congruent triangles",
        },
        { src: sss, text: "sss", label: "sss" },
        { src: sas, text: "sas", label: "sas" },
        { src: aas, text: "aas", label: "aas" },
        { src: hl, text: "hl", label: "hl" },
        { src: asa, text: "asa", label: "asa" },
        {
          src: flow_charts,
          text: "flowcharts",
          label: "congruent flow charts",
        },
        { src: converse, text: "converse", label: "converse" },
      ],
    },
    7: {
      text: ["circle properties", "mess around"],
      diagram: [
        {
          src: equation,
          text: "circle properties",
          label: "circle properties",
        },
        { src: reflection_symmetry, text: "mess around", label: "mess around" },
      ],
    },
    8: {
      text: [],
      diagram: [],
    },
  },
};

export const PageData = {
  one: {},
  two: {},
  three: {},
  triangle_sum: {},
  angle_relationships: {
    hints: [],
    extraPractice: [{}],
  },
  equations: {},
};
